In [14]:
cnf_matrix = [[0, 0, 1], [0, 9, 9], [0, 4, 77]]
cnf_matrix

[[0, 0, 1], [0, 9, 9], [0, 4, 77]]

In [15]:
import numpy as np
cnf_matrix = np.array(cnf_matrix)
print(cnf_matrix)

[[ 0  0  1]
 [ 0  9  9]
 [ 0  4 77]]


In [16]:
FP = cnf_matrix.sum(axis=0) - np.diag(cnf_matrix)
FN = cnf_matrix.sum(axis=1) - np.diag(cnf_matrix)
TP = np.diag(cnf_matrix)
TN = cnf_matrix.sum() - (FP + FN + TP)

In [17]:
FP = FP.astype(float)
FN = FN.astype(float)
TP = TP.astype(float)
TN = TN.astype(float)

In [18]:
recall = TP/(TP+FN)
print(recall)

[0.         0.5        0.95061728]


In [19]:
precision = TP/(TP+FP)
print(precision)

[       nan 0.69230769 0.88505747]


C:\Users\singh\AppData\Local\Temp\ipykernel_19312\1828884858.py:1: RuntimeWarning: invalid value encountered in divide
  precision = TP/(TP+FP)


In [20]:
acc = (TP+TN)/(TP+FP+FN+TN)
print(acc)

[0.99 0.87 0.86]


In [21]:
f1 = (2*precision*recall)/(precision+recall)
print(f1)

[       nan 0.58064516 0.91666667]
